### ISSUE TITLE
LateInitializationError: Field 'textureId' has not been initialized

### ISSUE THREAD

**Issue by ntvkhoasgt** [hpdragon1618/flutter_gstreamer_player#1]
Hi, i'm your big fan. 
When i added this plugin in to my project. Some log was happened. 
Please help to fix this

![image](https://user-images.githubusercontent.com/67872483/171534761-dced1ffa-fc8d-4526-86d3-3bdfc716d0c8.png)

**Comment by srix55** [comment]
Looks like the project is abandoned...

**Comment by hpdragon1618** [comment]
Hi @ntvkhoasgt, sorry for the late reply, I have been busy lately,

The reason I haven't use you approach from the beginning is because initialize `textureId` with `0` name may raise conflict with any other renderer that also use `0` name.
But according to [this](https://docs.gl/gl3/glIsTexture), `0` is not a name corresponds to a texture, initialize with `0` name should be non issue, so your approach is good.

I have merge your pull request, many thanks for your help.

I'm closing the issue, feel free to reach out if you have any concern.
